namespace DDB.CharacterService.v5;

public record Spells(
    IReadOnlyList<Spell> Race,
    IReadOnlyList<Spell> Class,
    IReadOnlyList<Spell> Background,
    IReadOnlyList<Spell> Item,
    IReadOnlyList<Spell> Feat,
    object OverrideSaveDc,
    LimitedUse LimitedUse,
    int Id,
    int EntityTypeId,
    SpellDefinition SpellDefinition,
    int DefinitionId,
    bool Prepared,
    bool CountsAsKnownSpell,
    bool UsesSpellSlot,
    object CastAtLevel,
    bool AlwaysPrepared,
    string Restriction,
    int? SpellCastingAbilityId,
    object DisplayAsAttack,
    object AdditionalDescription,
    bool CastOnlyAsRitual,
    object RitualCastingType,
    Range Range,
    Activation Activation,
    bool BaseLevelAtWill,
    object AtWillLimitedUseLevel,
    object IsSignatureSpell,
    int ComponentId,
    int ComponentTypeId,
    object SpellListId
) : Spell(
    OverrideSaveDc,
    LimitedUse,
    Id,
    EntityTypeId,
    SpellDefinition,
    DefinitionId,
    Prepared,
    CountsAsKnownSpell,
    UsesSpellSlot,
    CastAtLevel,
    AlwaysPrepared,
    Restriction,
    SpellCastingAbilityId,
    DisplayAsAttack,
    AdditionalDescription,
    CastOnlyAsRitual,
    RitualCastingType,
    Range,
    Activation,
    BaseLevelAtWill,
    AtWillLimitedUseLevel,
    IsSignatureSpell,
    ComponentId,
    ComponentTypeId,
    SpellListId
), ISourceAggregator<Spell>;